// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzmobambhlrawwvlnwwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6bW9iYW1iaGxyYXd3dmxud3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDk0MjAsImV4cCI6MjA2Mjg4NTQyMH0.TlZwQwEwwPI1HuWz1-wpiMnPty9YfwKxZ1mXz3ehUpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);