name: 🚀 Build & Deploy to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Copy .htaccess into dist
        run: cp .htaccess dist/.htaccess

      - name: Sync to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:       ${{ secrets.HOSTINGER_FTP_HOST }}
          username:     ${{ secrets.HOSTINGER_FTP_USER }}
          password:     ${{ secrets.HOSTINGER_FTP_PASS }}
          port:       21           # <-- add your FTP port here
          local-dir:    dist/
          server-dir:   ./
          